[pytest]
testpaths = tests
pythonpath = .
addopts = -s -v --alluredir=./reports/allure-results
markers =
    smoke: smoke test cases
    project: project api test cases
    module: module api test cases
    system: system api test cases
    document: document api test cases